name: deploy

on:
  push:
    branches:
    - master
 
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout sources
      uses: actions/checkout@v1
      
    - name: Build app
      run: hyoo-ru/mam_build@master
      - yarn install
      - yarn lint
      - yarn test
      - yarn build
      
    - name: Deploy on GitHub Pages
      uses: alex-page/blazing-fast-gh-pages-deploy@v1.0.1
      with:
        repo-token: ${{ secrets.GH_PAT }}
        site-directory: '.'
